# ignored on non-linux platforms, but bionic is required for nested virtualization
dist: bionic
language: java
branches:
    only:
        - master
cache:
    directories:
        - node_modules
jdk:
    - openjdk8
env:
    global:
        - COMPILE_API=29
        - ANDROID_BUILD_TOOLS=29.0.2
        - ANDROID_HOME=${HOME}/android-sdk
        - ANDROID_TOOLS_URL="https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip"
        # PATH order is incredibly important. e.g. the 'emulator' script exists in more than one place!
        - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools:${PATH}
jobs:
    fast_finish: true
    include:
        name: "Run android"
        before_install:
            # Set up JDK 8 for Android SDK - Java is universally needed: codacy, unit tests, emulators
            - ./install-emulator.sh
        install:
          # Set up KVM on linux for hardware acceleration. Manually here so it only happens for emulator tests, takes ~30s
            - sudo -E apt-get -yq --no-install-suggests --no-install-recommends install bridge-utils libpulse0 libvirt-bin qemu-kvm virtinst ubuntu-vm-builder >/dev/null
            - sudo adduser $USER libvirt
            - sudo adduser $USER kvm
            - echo no | avdmanager create avd --force -n Pixel_2_API_29 -k "system-images;android-${COMPILE_API};google_apis;x86_64" -c 100M # create device
            - sudo -E sudo -u "$USER" -E bash -c "${ANDROID_HOME}/emulator/emulator -avd Pixel_2_API_29 -no-snapshot -no-boot-anim -camera-back none -camera-front none -selinux permissive -qemu -m 2048 &"
            - echo 'Emu created'
            - ./android-wait-for-emulator.sh
            - adb shell input keyevent 82 & # unlocking the device
        before_script:
            - mkdir res && mkdir res/raw && touch res/raw/runtime_url && echo "https://travis2-sandbox.mxapps.io" > res/raw/runtime_url
            - zip -u app-appstore-debug.apk res/raw/runtime_url
            - echo android | ${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS}/apksigner sign --ks debug.keystore app-appstore-debug.apk
            - echo android | ${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS}/apksigner sign --ks debug.keystore app-appstore-debug-androidTest.apk
            - npm install
        script:
            - npm run test
