# ignored on non-linux platforms, but bionic is required for nested virtualization
dist: bionic
language: java
branches:
    only:
        - master
cache:
    directories:
        - ${HOME}/android-sdk
jdk:
    - openjdk8
env:
    global:
        - COMPILE_API=29
        - ANDROID_BUILD_TOOLS=29.0.2
        - ABI=x86_64
        - ADB_INSTALL_TIMEOUT=8
        - ANDROID_HOME=${HOME}/android-sdk
        - ANDROID_TOOLS_URL="https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip"
        - EMU_FLAVOR=google_apis # use google_apis flavor if no default flavor emulator
        - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
        - TOOLS=${ANDROID_HOME}/tools
        # PATH order is incredibly important. e.g. the 'emulator' script exists in more than one place!
        - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
jobs:
    fast_finish: true
    include:
        name: "Run android"
          # manually install the android-28
        before_install:
            # Set up JDK 8 for Android SDK - Java is universally needed: codacy, unit tests, emulators
            - wget -q "${ANDROID_TOOLS_URL}" -O android-sdk-tools.zip
            - unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
            - rm android-sdk-tools.zip
            - mkdir $HOME/.android
            - touch $HOME/.android/repositories.cfg
            - echo y | sdkmanager --licenses >/dev/null
            - echo y | sdkmanager --no_https "platform-tools" >/dev/null # adb logcat fastboot
            - echo y | sdkmanager --no_https "tools" >/dev/null #  avdmanager, sdkmanager
            - echo y | sdkmanager --no_https "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null # apk signed is needed
            - echo y | sdkmanager --no_https "platforms;android-${COMPILE_API}" >/dev/null # actual image
            - echo y | sdkmanager --no_https "emulator" >/dev/null # duh
            - echo 'Finished installing packages'
        install:
            - echo y | sdkmanager --no_https "system-images;android-$COMPILE_API;$EMU_FLAVOR;$ABI" # install our emulator
            # Set up KVM on linux for hardware acceleration. Manually here so it only happens for emulator tests, takes ~30s
            - sudo -E apt-get -yq --no-install-suggests --no-install-recommends install bridge-utils libpulse0 libvirt-bin qemu-kvm virtinst ubuntu-vm-builder >/dev/null
            - sudo adduser $USER libvirt
            - sudo adduser $USER kvm

            - echo no | avdmanager create avd --force -n TEST_DEVICE -k "system-images;android-$COMPILE_API;$EMU_FLAVOR;$ABI" -c 100M # create device
            - |
                EMU_PARAMS="-verbose -no-snapshot -no-window -camera-back none -camera-front none -selinux permissive -qemu -m 2048"
                EMU_COMMAND="emulator"
                sudo -E sudo -u $USER -E bash -c "${ANDROID_HOME}/emulator/${EMU_COMMAND} -avd TEST_DEVICE ${EMU_PARAMS} &"
            - echo 'Emu created'
            - chmod +x ./android-wait-for-emulator.sh
            - ./android-wait-for-emulator.sh
            - adb shell input keyevent 82 & # unlocking the device
            - adb -s  @TEST_DEVICE install app-appstore-debug.apk
        script:
            - echo 'Done'
