# ignored on non-linux platforms, but bionic is required for nested virtualization
branches:
    only:
        - master
cache:
    directories:
        - node_modules
env:
    global:
        - COMPILE_API=29
        - ANDROID_BUILD_TOOLS=29.0.2
        - ANDROID_HOME=${HOME}/android-sdk
        - ANDROID_TOOLS_URL="https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip"
        # PATH order is incredibly important. e.g. the 'emulator' script exists in more than one place!
        - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools:${PATH}
        - LATEST_NATIVE_TEMPLATE_VERSION=$(git -c 'versionsort.suffix=-' ls-remote --exit-code --refs --sort='version:refname' --tags https://github.com/mendix/native-template '*.*.*'  | tail -n 1 | cut -d "/" -f 3)
        - LATEST_CURRENT_VERSION=$(git -c 'versionsort.suffix=-' ls-remote --exit-code --refs --sort='version:refname' --tags https://github.com/mendixlabs/travisAndroid '*.*.*'  | tail -n 1 | cut -d "/" -f 3)
stages:
    - name: test
      if: LATEST_NATIVE_TEMPLATE_VERSION != LATEST_CURRENT_VERSION
jobs:
    fast_finish: true
    include:
          - name: "Prepare apk"
            os: osx
            osx_image: xcode11.6
            language: java
            jdk:
                - openjdk9
            script:
                - ./install-android-tools.sh
                - curl "https://github.com/mendix/native-template/archive/${LATEST_NATIVE_TEMPLATE_VERSION}.zip" -L -o ./native-template.zip
                - unzip native-template.zip
                - cd native-template-${LATEST_NATIVE_TEMPLATE_VERSION:1}
                - npm install
                - cd android
                - ./gradlew assembleAppstoreDebug assembleAppstoreDebugAndroidTest -DtestBuildType=debug
                - mkdir -p $HOME/app/android
                - mv app/build/outputs/apk/appstore/debug/app-appstore-debug.apk $HOME/app/android/
                - mv app/build/outputs/apk/androidTest/appstore/debug/app-appstore-debug-androidTest.apk $HOME/app/android/
            before_deploy:
                # Set up git user name and tag this commit
                - git config --local user.name $GITHUB_USER
                - git config --local user.email $GITHUB_EMAIL
                - export TRAVIS_TAG=${TRAVIS_TAG:-$VERSION}
                - git tag $TRAVIS_TAG
            deploy:
                provider: releases
                api_key: $API_KEY
                file_glob: true
                file: ${HOME}/app/android/*
                skip_cleanup: true
          - name: "Prepare ipa"
            os: osx
            osx_image: xcode11.6
            script:
                - curl https://github.com/mendix/native-template/archive/${LATEST_NATIVE_TEMPLATE_VERSION}.zip -L -o ./native-template.zip
                - unzip native-template.zip
                - cd native-template-${LATEST_NATIVE_TEMPLATE_VERSION:1}
                - npm install
                - cd ios
                - pod install
                - xcodebuild -quiet -workspace ./NativeTemplate.xcworkspace -scheme nativeTemplate -configuration Debug -sdk iphonesimulator -derivedDataPath ./build
                - mkdir -p $HOME/app/ios
                - zip -r $HOME/app/ios/NativeTemplate.zip $(pwd)/build/Build/Products/Debug-iphonesimulator/NativeTemplate.app
            before_deploy:
                # Set up git user name and tag this commit
                - git config --local user.name $GITHUB_USER
                - git config --local user.email $GITHUB_EMAIL
                - export TRAVIS_TAG=${TRAVIS_TAG:-$VERSION}
                - git tag $TRAVIS_TAG
            deploy:
                provider: releases
                api_key: $API_KEY
                file_glob: true
                file: ${HOME}/app/ios/*
                skip_cleanup: true
