# ignored on non-linux platforms, but bionic is required for nested virtualization
dist: bionic
language: java
branches:
    only:
        - master
cache:
    directories:
        - ${HOME}/android-sdk/
jdk:
    - openjdk8
env:
    global:
        - COMPILE_API=29
        - ANDROID_BUILD_TOOLS=29.0.2
        - ANDROID_HOME=${HOME}/android-sdk
        - ANDROID_SDK_ROOT=${ANDROID_HOME}
        - ANDROID_TOOLS_URL="https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip"
        # PATH order is incredibly important. e.g. the 'emulator' script exists in more than one place!
        - TOOLS=${ANDROID_HOME}/tools
        # PATH order is incredibly important. e.g. the 'emulator' script exists in more than one place!
        - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
jobs:
    fast_finish: true
    include:
        name: "Run android"
        install:
            # Set up JDK 8 for Android SDK - Java is universally needed: codacy, unit tests, emulators
            - ./install-emulator.sh
        script:
            - ./create-emulator.sh
            - ./android-wait-for-emulator.sh
            - adb shell input keyevent 82 & # unlocking the device
